### ISSUE TITLE
Django > 3.2 not supported

### ISSUE THREAD

**Issue by JElgar** [django-tiptap/django_tiptap#10]
Is it possible to remove/bump the max-supported Django version or is this limit required?

https://github.com/django-tiptap/django_tiptap/blob/32d044d3c9db56381fe791cdef4a3d1ac96d85fa/pyproject.toml#L12

**Comment by solen0id** [comment]
Yeah, should be fine :+1:

**Comment by solen0id** [comment]
Fixed in https://github.com/django-tiptap/django_tiptap/releases/tag/v0.0.10

**Comment by JElgar** [comment]
Thank you!
